### ISSUE TITLE
non static method

### ISSUE THREAD

**Issue by antonioreyna** [nztim/logger#2]
now im getting this:

```
Non-static method NZTim\\Logger\\Logger::info() should not be called statically
```

**Comment by antonioreyna** [comment]
oh i just need to `use Logger;` not the whole namespace

**Comment by antonioreyna** [comment]
is it possible to change the directory other than `custom`? for specific logs?

**Comment by nztim** [comment]
Not at present, the `custom` subfolder is hard coded. 

How would that work?

**Comment by antonioreyna** [comment]
it would be great to use dot notacion for example to have a better order on logs 
```
Logger::info('payments.success', 'message');
Logger::info('payments.error', 'message');
```

or something like that and maybe get rid of custom directory when at least one dot added :)

**Comment by nztim** [comment]
Yes I see what you mean. It would be nice the paths to behave similarly to view templates, where there is a configurable base folder where logs are stored if there is no dot. If there is a dot then the log is stored in a subfolder of that location.

The config base would be set to `custom` by default, so everything works the same as it does now. 
But if you changed the base folder to `''`, then you would be working from the `storage/logs` folder, like this:

```
Logger::info('auth', 'Message'); // storage/logs/auth.log
Logger::info('payments.success', 'Message'); // storage/logs/payments/success.log
```

How does that sound? I'll have a go and see how it looks.

**Comment by antonioreyna** [comment]
that look great exactly what i was imagine :D

**Comment by nztim** [comment]
v0.5.1 is up, please give it a try

**Comment by antonioreyna** [comment]
im trying to update with composer but looks like it cant find the new version?

**Comment by antonioreyna** [comment]
works as a charm!! thank you so much @nztim this is an awesome library, if you let us customize maybe the base directory in the config file or something so instead of `custom` we can set something different would be also great but by now this new feature makes this library more amazing :D

**Comment by nztim** [comment]
Yes that's already in there, just add the 'folder' key to the config file:
https://github.com/nztim/logger/blob/master/src/config/logger.php#L9

**Comment by antonioreyna** [comment]
thats awesome! thank you!
