### ISSUE TITLE
Daily logs

### ISSUE THREAD

**Issue by antonioreyna** [nztim/logger#3]
Hi again, maybe another feature could be having the ability to set in the config if the logs will be daily to create files with the date in the name and even if global config maybe being able to override for specific logs or something like in the `Logger::info($path, $message, $context, $daily)`

I think we can do that concatenating the desired date to the $path like `'auth.access-2017-02-01'`

**Comment by nztim** [comment]
That's a good idea and Monolog already implements the code for this, although I'm not so sure about adding a parameter. I've uploaded v0.6 where you can set a logfile to be daily via the config file, take a look.

**Comment by antonioreyna** [comment]
```
'daily' => [] list of log files to be handled as daily logs
```

So the path of the logs like `['auth.access', 'auth.error']` and so on?

**Comment by antonioreyna** [comment]
and here...

```
'max_daily' => 7 maximum number of daily log files to keep
```

the log files will be removed after 7 days?

**Comment by nztim** [comment]
Yes the config changes are per the readme and the diff:
https://github.com/nztim/logger/commit/7ebae0b3117309e0e294ffd795e2e6e2557eb87c#diff-9cd1af3df4649bbb474347902ecb23e5

> So the path of the logs like ['auth.access', 'auth.error'] and so on?

Yes

>the log files will be removed after 7 days?

It keeps the most recent 7 log files. This is done by monolog, same as Laravel daily logs.

**Comment by antonioreyna** [comment]
nice , so not to worry about filling the server with logs :D thanks!!!
